### ISSUE TITLE
Does not support finer layers or supports

### ISSUE THREAD

**Issue by haarp** [eoprede/prusa_profiles#10]
Hello,

I am testing the Pretty filament profiles in Slic3r. They do seem to make a difference in the 0.2mm prints, thanks for that!

However I notice that with the Pretty PETG filament profile active, I am unable to build supports. They simply do not appear on the part. Likewise, finer layers than 0.20mm can be selected, but also do not appear on the part.

Is this intentional? Am I doing something wrong? Thanks!

**Comment by talldonkey** [comment]
The main thing is that this is not the channel to report a bug or issues
with the profile. This is just a collection of profiles. Try asking in the
Prusa Community Facebook group.
