### ISSUE TITLE
Planning to add new

### ISSUE THREAD

**Issue by Dutchy-79** [eoprede/prusa_profiles#11]
HI,

Are you planning to add the new profiles like 
Prusa Pretty PLA V3a(7x7).fff
Prusa Pretty PETG V3a(7x7).fff
Pretty PETG V3a(7x7).ini
Pretty HTPLA.ini

from the facebook group. https://www.facebook.com/groups/prusacommunity/files/

Regards,

Jasper

**Comment by eoprede** [comment]
@Dutchy-79 
I was under impression that they are still in beta. Isn't that the case?

**Comment by Dutchy-79** [comment]
You might be right, they are made for a custom firmware though prusa said they will add 7*7 bed leveling soon.

There's one other I haven't seen here yet I think it's plaht or htpla

**Comment by Dutchy-79** [comment]
You might be right, they are made for a custom firmware though prusa said they will add 7*7 bed leveling soon.

There's one other I haven't seen here yet I think it's plaht or htpla
