### ISSUE TITLE
Unable to load config file

### ISSUE THREAD

**Issue by PCFrog** [eoprede/prusa_profiles#13]
I receive this error.

![error](https://user-images.githubusercontent.com/48536115/54321249-9e1c3280-45c6-11e9-9573-251794116a9a.PNG)

**Comment by trevjonez** [comment]
what version of slic3r wrote the ini file and what version is trying to import it? they have been changing a ton of things perhaps they changed some ini file parsing? if so it might be worth reporting to the main repo that it is failing to import configs.

**Comment by eoprede** [comment]
Did you see this note on the front page of the repo: 
Since this seems to be the common issue: please make sure that you either download archive of all the files, make git clone or download a raw file. Attempting to copy-paste the file or downloading a file from regular github view (non-raw) will result in errors while importing.
That's the most common reason for having issues.

**Comment by PCFrog** [comment]
> Did you see this note on the front page of the repo:
> Since this seems to be the common issue: please make sure that you either download archive of all the files, make git clone or download a raw file. Attempting to copy-paste the file or downloading a file from regular github view (non-raw) will result in errors while importing.
> That's the most common reason for having issues.

Feeling sheepish...  That one statement was just out of my browser window view.  After following that it worked. Thanks for pointing it out.

**Comment by ochm** [comment]
The same error while trying to import Pretty PETG v3 to PrusaSlicer 2.0.0
Failed loading the preset file: C:\Users\PC\Desktop\PrettyPETGV3.ini
Reason: <unspecified file>(1): '=' character not found in line
The content of ini file is created by copy/paste from raw data on github.
[PrettyPETGV3.zip](https://github.com/eoprede/prusa_profiles/files/3536307/PrettyPETGV3.zip)
Pretty PLA v4 can be imported without any issue.
