### ISSUE TITLE
Which Settings are for Petg 0.6 Nozzle?

### ISSUE THREAD

**Issue by myke8950** [eoprede/prusa_profiles#14]
I am trying to print using your settings for a 0.6 nozzle using PETG, possibly 1mm eventually, and the only parameter setup I see is vase 0.6 and I am not sure what that is going to do. Can you set up the code defining it in the title for normal prints using the 0.4 and a separate one for 0.6 and so on if you kindly keep adding more. Your code is fantastic btw! I just want to be able to print faster and I am unsure of what code to change in the overall PrusaSlic3r.

**Comment by eoprede** [comment]
Sorry, I am not an expert in profiles, I just keep collection for stock Prusa printers here. Your best bet to find the answer is to go to facebook group.
