### ISSUE TITLE
dont load

### ISSUE THREAD

**Issue by viczena** [eoprede/prusa_profiles#3]
Hi, i am using Slic3r prusa edition 1.40.1+win64 and i cannot load your profiles. I always get

<unspecified file> (7): ´=´character not found in line

error

**Comment by hutje** [comment]
Same

**Comment by eoprede** [comment]
Did you this in repo's main page: "please make sure that you either download archive of all the files, make git clone or download a raw file. Attempting to copy-paste the file or downloading a file from regular github view (non-raw) will result in errors while importing."

**Comment by hutje** [comment]
Yeah, I found out just yet. I did copy the raw text, this worked.
