### ISSUE TITLE
After first layer nozzle temperature decreases to 200C

### ISSUE THREAD

**Issue by hutje** [eoprede/prusa_profiles#6]
After first layer nozzle temperature decreases to 200C but it needs to be 210C.
When I tune during print to 220C it still stays 10C under the desired temperature...
This causes inconsistent print layers

**Comment by eoprede** [comment]
I would recommend googling this "issue", as it is feature of Cura.

**Comment by hutje** [comment]
Cura? I use pretty PLA v3 for Slic3r...

**Comment by eoprede** [comment]
Well, sorry, my crystal ball was off today. Regardless, google how to configure Slicer. It is not a profile issue.
