### ISSUE TITLE
Temp drop on layer change

### ISSUE THREAD

**Issue by Dutchy-79** [eoprede/prusa_profiles#8]
I'm using Pretty PLA V3 and after layer 1 the temp drops 5c and the fan comes on full, The combination makes the temp drop quite fast and below setpoint.

Maybe Chris could consider dropping the temp on layer 2 after the fan is on, Or fan 50% and then layer 3 100%
![temp drop mk3 pla](https://user-images.githubusercontent.com/22749572/47614730-870bf680-daa4-11e8-8fb5-0dbc59dbbc91.jpg)

**Comment by eoprede** [comment]
Two things: 
1. I have not created any of these profiles, I am just merely maintaining a collection for people to have one easy spot to download them from. I am afraid most of the profile creators don't work much with GIT and unfortunately don't have direct involvement with this repo.
2. None of the profiles are going to work perfect for your particular printer. They all require slight tweaking. Specific to this temp dip - it has been an issue for me in one print out of hundred, which I solved by reducing temperature by 3 degrees over 3 layers.

I would imagine there is a way to slowly increase fan speed (or slowly decrease temp) over course of 10-20 seconds to avoid this dip - but unfortunately I am not a GCODE master and I don't know it. Chris is certainly one of the most knowledgeable people in the Facebook group when it comes to profiles, but he's not the only one. 
I think the best course of action would be to create discussion in Prusa Community Forum regarding this issue. Once solution is found, I am sure Chris will incorporate it in his future versions of profiles.

**Comment by Dutchy-79** [comment]
Thanks, I will ask on Facebook.
