### ISSUE TITLE
MK3 Speed Profile PLA inhibits supports?

### ISSUE THREAD

**Issue by marhar** [eoprede/prusa_profiles#9]
Very strange thing.  As you can see from the attached screenshots, Setting Printer to "MK3 Speed Profile PLA" disables supports.  All other config parameters are the same.

Any hints as to what might be awry?
<img width="1192" alt="snapz003" src="https://user-images.githubusercontent.com/7154/47969230-2b53e700-e029-11e8-81fc-89f47fd8f070.png">
<img width="1192" alt="snapz011" src="https://user-images.githubusercontent.com/7154/47969234-36a71280-e029-11e8-8bb9-133ccfed4354.png">

**Comment by Dutchy-79** [comment]
Open print settings and turn support on.

**Comment by marhar** [comment]
> Open print settings and turn support on.

Yep, that's on in both cases.

**Comment by Dutchy-79** [comment]
So "Generate support material" and "Auto generated supports" are on and the "Overhang threshold" as at 45 or more?

**Comment by marhar** [comment]
> So "Generate support material" and "Auto generated supports" are on and the "Overhang threshold" as at 45 or more?

Correct.  It works as expected with the stock printer profile "Original Prusa i3 MK3".  It seems there's more parameters specified in the config files than are in the GUI.

Current workaround is to use a modified stock profile, with pre and post gcode copied from Fast.  This is working well enough so no urgency, but it does seem odd that there's something in the config that stops support generation.

**Comment by Dutchy-79** [comment]
Maybe the profile is meant for a different version.
